### ISSUE TITLE
BUG:Species file for xx not found

### ISSUE THREAD

**Issue by TDKOLI** [materialsproject/atomate2#1003]
I met this issue when I use phonon flow and md flow for vasp, when I did relax job for some structures, none of them met the error says 
Species file for xx not found, but when I use these flows, I met this issue for every structure(no matter what elements are, I will encounter this error).
My code is just like the tutorial one,
poscar = Poscar.from_file("POSCAR")
structure = poscar.structure
phonon_maker = PhononMaker(
    get_supercell_size_kwargs={'supercell_matrix': [[2, 0, 0],
                                                    [0, 2, 0],
                                                    [0, 0, 2]]}
)
phonon_flow = phonon_maker.make(structure)
new_flow = update_user_incar_settings(phonon_flow,{"ENCUT": 520})
new_flow.update_metadata({"structure_index": "185711_Al-222_phonon"})
run_locally(new_flow, create_folders=True)

**Comment by utf** [comment]
Please can you post the full error message.

**Comment by JaGeo** [comment]
Could you describe the error in a bit more detail, i e. Add the full output and also the full code to reproduce?

**Comment by TDKOLI** [comment]
Many thanks, sorry I did not post the error info, here is the full error info: 2024-09-30 17:29:26,330 INFO Started executing jobs locally
2024-09-30 17:29:26,358 INFO Starting job - Relaxation calculation (d9df7fee-d0b7-4352-bf07-8560c3756565)
2024-09-30 17:29:26,432 INFO Relaxation calculation failed with exception:
Traceback (most recent call last):
  File "/home/ucl/modl/hayu/miniconda3/envs/mace/lib/python3.11/site-packages/jobflow/managers/local.py", line 114, in _run_job
    response = job.run(store=store)
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/ucl/modl/hayu/miniconda3/envs/mace/lib/python3.11/site-packages/jobflow/core/job.py", line 600, in run
    response = function(*self.function_args, **self.function_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ucl/modl/hayu/miniconda3/envs/mace/lib/python3.11/site-packages/atomate2/aims/jobs/base.py", line 107, in make
    write_aims_input_set(
  File "/home/ucl/modl/hayu/miniconda3/envs/mace/lib/python3.11/site-packages/atomate2/aims/files.py", line 118, in write_aims_input_set
    aims_is = input_set_generator.get_input_set(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ucl/modl/hayu/miniconda3/envs/mace/lib/python3.11/site-packages/pymatgen/io/aims/sets/base.py", line 224, in get_input_set
    return AimsInputSet(parameters=parameters, structure=structure, properties=properties)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ucl/modl/hayu/miniconda3/envs/mace/lib/python3.11/site-packages/pymatgen/io/aims/sets/base.py", line 58, in __init__
    aims_control_in, aims_geometry_in = self.get_input_files()
                                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ucl/modl/hayu/miniconda3/envs/mace/lib/python3.11/site-packages/pymatgen/io/aims/sets/base.py", line 88, in get_input_files
    aims_control_in.get_content(structure=self._structure),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ucl/modl/hayu/miniconda3/envs/mace/lib/python3.11/site-packages/pymatgen/io/aims/inputs.py", line 548, in get_content
    content += self.get_species_block(structure, species_dir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ucl/modl/hayu/miniconda3/envs/mace/lib/python3.11/site-packages/pymatgen/io/aims/inputs.py", line 618, in get_species_block
    raise ValueError(f"Species file for {sp.symbol} not found.")
ValueError: Species file for Hf not found.

2024-09-30 17:29:26,434 INFO Finished executing jobs locally
My full code to reproduce is the one I put above, it can be any structure in my case, here are the full code with import: from atomate2.aims.flows.phonons import PhononMaker
from atomate2.vasp.powerups import add_metadata_to_flow
from pymatgen.core import Structure
from atomate2.vasp.powerups import update_user_incar_settings
from pymatgen.io.vasp import Poscar
from monty.serialization import dumpfn
from atomate2.vasp.sets.core import RelaxSetGenerator
from jobflow import Flow
from jobflow import run_locally, JobStore
poscar = Poscar.from_file("/home/batch2poscar/POSCAR_185711")
structure = poscar.structure

phonon_maker = PhononMaker(
    get_supercell_size_kwargs={'supercell_matrix': [[2, 0, 0],
                                                    [0, 2, 0],
                                                    [0, 0, 2]]}
)

phonon_flow = phonon_maker.make(structure)
new_flow = update_user_incar_settings(phonon_flow,{"ENCUT": 520})
new_flow.update_metadata({"structure_index": "185711_phonon"})

run_locally(new_flow, create_folders=True)

**Comment by JaGeo** [comment]
@TDKOLI There is another PhononMaker in the VASP submodules. You should import this one. Currently, you are using the AIMS one.

**Comment by TDKOLI** [comment]
Ah, yes, sorry, I'm silly, I forgot to delete this import, I had one for vasp. Thank you, sorry to bother you with such problem.

**Comment by JaGeo** [comment]
@TDKOLI no worries! It happens :). Always happy to see that the workflows are used :)
