### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by orionarcher** [materialsproject/atomate2#1022]
**Describe the bug**
@falletta and I are trying to get cp2k running with atomate2 but are unable to generate an input set. We wrote a simple script based on the tests in `tests/cp2k/sets/test_core.py` and our call to `get_input_set` was failing with the following error. Oddly, the tests are running fine, even though this script is nearly identical to the test. What are we missing here? @nwinner wrote the relevant cp2k code.

**To Reproduce**
```python
from pymatgen.core import Structure
from atomate2.cp2k.sets.core import StaticSetGenerator

structure = Structure.from_file(
    "/Users/orioncohen/Radical/repos/atomate2/tests/test_data/structures/Si.cif"
)

basis_and_potential = {
    "basis_and_potential": {
        "Si": {
            "basis": "DZVP-MOLOPT-SR-GTH",
            "potential": "GTH-PBE-q4",
            "aux_basis": "pFIT3",
        }
    }
}

generator = StaticSetGenerator(user_input_settings=basis_and_potential)
input_set = generator.get_input_set(structure)
```

The full error is:
```
/Users/orioncohen/miniforge3/envs/radical4/lib/python3.12/site-packages/pymatgen/io/cp2k/sets.py:229: UserWarning: As of 2022.1, kpoints not supported with OT. Defaulting to diagonalization
  warnings.warn("As of 2022.1, kpoints not supported with OT. Defaulting to diagonalization")
/Users/orioncohen/miniforge3/envs/radical4/lib/python3.12/site-packages/pymatgen/io/cp2k/sets.py:515: UserWarning: Unable to validate basis for Si. Exact name provided will be put in input file.
  warnings.warn(f"Unable to validate basis for {el}. Exact name provided will be put in input file.")
/Users/orioncohen/miniforge3/envs/radical4/lib/python3.12/site-packages/pymatgen/io/cp2k/sets.py:519: UserWarning: Unable to validate auxiliary basis for Si. Exact name provided will be put in input file.
  warnings.warn(
/Users/orioncohen/miniforge3/envs/radical4/lib/python3.12/site-packages/pymatgen/io/cp2k/sets.py:526: UserWarning: Unable to validate potential for Si. Exact name provided will be put in input file.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/orioncohen/Radical/repos/atomate2/tests/cp2k/sets/throwaway_script.py", line 20, in <module>
    input_set = generator.get_input_set(structure)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/orioncohen/Radical/repos/atomate2/src/atomate2/cp2k/sets/base.py", line 221, in get_input_set
    cp2k_input = self._get_input(
                 ^^^^^^^^^^^^^^^^
  File "/Users/orioncohen/Radical/repos/atomate2/src/atomate2/cp2k/sets/base.py", line 331, in _get_input
    cp2k_input = DftSet(structure=structure, kpoints=kpoints, **input_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/orioncohen/miniforge3/envs/radical4/lib/python3.12/site-packages/pymatgen/io/cp2k/sets.py", line 280, in __init__
    self.basis_and_potential = DftSet.get_basis_and_potential(self.structure, self.basis_and_potential)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/orioncohen/miniforge3/envs/radical4/lib/python3.12/site-packages/pymatgen/io/cp2k/sets.py", line 536, in get_basis_and_potential
    pfn2 = potential.filename
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'filename'
```

**Comment by orionarcher** [comment]
Nevermind, found the underlying issue!

**Comment by JaGeo** [comment]
Maybe someone could document this nevertheless in our documentation?
