### ISSUE TITLE
BUG: AttributeError: 'CompleteDos' object has no attribute 'get_band_filling' when running DielectricMaker()

### ISSUE THREAD

**Issue by janosh** [materialsproject/atomate2#124]
Getting a strange bug at the very end of a DFPT calc which sadly means none of the results make it into the DB. Not sure where to start debugging, if someone else has any ideas, I'm all ears.

Stack trace:

```py
INFO:jobflow.managers.local:dielectric failed with exception:
Traceback (most recent call last):
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/jobflow/managers/local.py", line 97, in _run_job
    response = job.run(store=store)
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/jobflow/core/job.py", line 524, in run
    response = function(*self.function_args, **self.function_kwargs)
  File "/Users/janosh/dev/atomate2/src/atomate2/vasp/jobs/base.py", line 150, in make
    task_doc = TaskDocument.from_directory(Path.cwd(), **self.task_document_kwargs)
  File "/Users/janosh/dev/atomate2/src/atomate2/vasp/schemas/task.py", line 323, in from_directory
    calc_doc, vasp_objects = Calculation.from_vasp_files(
  File "/Users/janosh/dev/atomate2/src/atomate2/vasp/schemas/calculation.py", line 646, in from_vasp_files
    output_doc = CalculationOutput.from_vasp_outputs(
  File "/Users/janosh/dev/atomate2/src/atomate2/vasp/schemas/calculation.py", line 458, in from_vasp_outputs
    _get_band_props(vasprun.complete_dos, structure)
  File "/Users/janosh/dev/atomate2/src/atomate2/vasp/schemas/calculation.py", line 814, in _get_band_props
    "filling": complete_dos.get_band_filling(band=orb_type, elements=[el]),
AttributeError: 'CompleteDos' object has no attribute 'get_band_filling'
```

The error originates on this line:

https://github.com/materialsproject/atomate2/blob/b4ccbb17996c81109f93f48e1668a59bf870fe08/src/atomate2/vasp/schemas/calculation.py#L814

<details>
<summary>full job logs</summary>

```py
 2022-04-22 16:03:35,889 INFO Started executing jobs locally
2022-04-22 16:03:36,026 INFO Starting job - dielectric (336db245-27b5-4316-9a64-203065a61b9a)
WARNING in EDDRMM: call to ZHEGV failed
ERROR:custodian.custodian:VaspErrorHandler
No matching processes belonging to you were found
2022-04-23 17:26:50,175 INFO dielectric failed with exception:

INFO:jobflow.managers.local:dielectric failed with exception:
Traceback (most recent call last):
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/jobflow/managers/local.py", line 97, in _run_job
    response = job.run(store=store)
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/jobflow/core/job.py", line 524, in run
    response = function(*self.function_args, **self.function_kwargs)
  File "/Users/janosh/dev/atomate2/src/atomate2/vasp/jobs/base.py", line 150, in make
    task_doc = TaskDocument.from_directory(Path.cwd(), **self.task_document_kwargs)
  File "/Users/janosh/dev/atomate2/src/atomate2/vasp/schemas/task.py", line 323, in from_directory
    calc_doc, vasp_objects = Calculation.from_vasp_files(
  File "/Users/janosh/dev/atomate2/src/atomate2/vasp/schemas/calculation.py", line 646, in from_vasp_files
    output_doc = CalculationOutput.from_vasp_outputs(
  File "/Users/janosh/dev/atomate2/src/atomate2/vasp/schemas/calculation.py", line 458, in from_vasp_outputs
    _get_band_props(vasprun.complete_dos, structure)
  File "/Users/janosh/dev/atomate2/src/atomate2/vasp/schemas/calculation.py", line 814, in _get_band_props
    "filling": complete_dos.get_band_filling(band=orb_type, elements=[el]),
AttributeError: 'CompleteDos' object has no attribute 'get_band_filling'

2022-04-23 17:26:50,176 INFO Finished executing jobs locally
INFO:jobflow.managers.local:Finished executing jobs locally
Traceback (most recent call last):
  File "/Users/janosh/dev/vasp/atomate2/perovskite-diel.py", line 41, in <module>
    run_locally(diel_job, create_folders=True, ensure_success=True)
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/jobflow/managers/local.py", line 165, in run_locally
    raise RuntimeError("Flow did not finish running successfully")
RuntimeError: Flow did not finish running successfully
```
</details>

Job script

```py
import os
import warnings
from time import perf_counter

from atomate2.vasp.jobs.core import DielectricMaker
from atomate2.vasp.powerups import (
    update_user_incar_settings,
    update_user_kpoints_settings,
)
from jobflow import run_locally
from pymatgen.ext.matproj import MPRester
from pymatgen.io.vasp import Kpoints


os.environ["OMP_NUM_THREADS"] = "1"

warnings.filterwarnings("ignore")  # ignore pymatgen warnings clogging up the logs


SrHfO3 = MPRester().get_structure_by_material_id("mp-13108")


# make a relax job to optimise the structure
diel_job = DielectricMaker().make(SrHfO3)


diel_job = update_user_incar_settings(
    diel_job, {"ENCUT": 700, "EDIFF": 1e-7, "NELM": 40}
)
auto_kpts = Kpoints.automatic_density(SrHfO3, 3000)

diel_job = update_user_kpoints_settings(diel_job, auto_kpts)

start = perf_counter()

run_locally(diel_job, create_folders=True)

elapsed = perf_counter() - start
print(f"SrHfO3 DFPT calc took {elapsed:.1f} sec")
```

**Comment by arosen93** [comment]
Hey @janosh. Sorry to hear about your calculations not making it into the DB. This seems related to a PR of mine recently: https://github.com/materialsproject/atomate2/pull/86. I will take a look at this and get back to you.

**Comment by arosen93** [comment]
Looks like this is because you are using an outdated pymatgen. You should upgrade to the version in `setup.py` or `requirements.py`, but regardless it will need to be >= v2022.3.22 to have the band-related features mentioned here.

**Comment by utf** [comment]
@arosen93 would you mind updating the minimum version of pymatgen in setup.py and submitting a PR?
________________________________

**Comment by arosen93** [comment]
@janosh and I are DM'ing, and he's already on it :)
