### ISSUE TITLE
BUG: A blank `~/.atomate2.yaml` file causes a crash

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/atomate2#499]
If the user has a `~/.atomate2.yaml` file and it's blank, the following error is raised:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/site-packages/atomate2/__init__.py", line 6, in <module>
    SETTINGS = Atomate2Settings()
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Atomate2Settings
__root__
  'NoneType' object is not iterable (type=type_error)
```

**Comment by arosen93** [comment]
Linking to https://github.com/materialsproject/jobflow/issues/411.
