### ISSUE TITLE
BUG: Error in running bandstructure workflow

### ISSUE THREAD

**Issue by nhew1994** [materialsproject/atomate2#616]
**Describe the bug**
I'm going through the atomate2 bandstructure tutorial: https://materialsproject.github.io/atomate2/user/running-workflows.html. 

After I submit my job, I get the following error:
2023-11-19 21:50:11,122 INFO Started executing jobs locally
2023-11-19 21:50:11,126 INFO Starting job - relax 1 (eaba6cfb-64af-45f2-b9a0-616a23bf98cd)
2023-11-19 21:50:33,584 INFO Finished job - relax 1 (eaba6cfb-64af-45f2-b9a0-616a23bf98cd)
2023-11-19 21:50:33,585 WARNING Response.stored_data is not supported with local manager.
2023-11-19 21:50:33,588 INFO Starting job - relax 2 (772ed0c5-8a6d-4ee8-8ae5-d74da60dd2ce)
2023-11-19 21:50:33,698 INFO relax 2 failed with exception:
Traceback (most recent call last):
  File "/storage/home/njh5724/.conda/envs/atomate2/lib/python3.9/site-packages/jobflow/managers/local.py", line 102, in _run_job
    response = job.run(store=store)
  File "/storage/home/njh5724/.conda/envs/atomate2/lib/python3.9/site-packages/jobflow/core/job.py", line 572, in run
    self.resolve_args(store=store)
  File "/storage/home/njh5724/.conda/envs/atomate2/lib/python3.9/site-packages/jobflow/core/job.py", line 678, in resolve_args
    resolved_args = find_and_resolve_references(
  File "/storage/home/njh5724/.conda/envs/atomate2/lib/python3.9/site-packages/jobflow/core/reference.py", line 458, in find_and_resolve_references
    resolved_references = resolve_references(
  File "/storage/home/njh5724/.conda/envs/atomate2/lib/python3.9/site-packages/jobflow/core/reference.py", line 353, in resolve_references
    resolved_references[ref] = ref.resolve(
  File "/storage/home/njh5724/.conda/envs/atomate2/lib/python3.9/site-packages/jobflow/core/reference.py", line 178, in resolve
    data = MontyDecoder().process_decoded(data)
  File "/storage/home/njh5724/.conda/envs/atomate2/lib/python3.9/site-packages/monty/json.py", line 484, in process_decoded
    return cls_(**data)
  File "/storage/home/njh5724/.conda/envs/atomate2/lib/python3.9/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
  File "/storage/home/njh5724/.conda/envs/atomate2/lib/python3.9/site-packages/monty/json.py", line 263, in validate_monty_v2
    return cls._validate_monty(__input_value)
  File "/storage/home/njh5724/.conda/envs/atomate2/lib/python3.9/site-packages/monty/json.py", line 246, in _validate_monty
    new_obj = cls(**__input_value)
TypeError: __init__() got an unexpected keyword argument 'ALGO'

2023-11-19 21:50:33,705 INFO Finished executing jobs locally

I am using monty==2023.11.3
Let me know if you need any more information or if you know how to fix this problem.

**Comment by utf** [comment]
Thanks for the bug report. There seems to be an incompatibility with the latest `emmet` and `monty` versions.

@janosh are you able to look into this?

**Comment by utf** [comment]
@nhew1994 could you try updating `emmet`?

**Comment by nhew1994** [comment]
Thanks @utf for the reply. Do you mean emmet-core? When I do pip install atomate2, there is no emmet, only emmet-core. I'm trying different versions of emmet-core at the moment.

**Comment by utf** [comment]
Yep, I meant emmet-core. Let me know if a more recent version of emmet fixes it for you.

**Comment by nhew1994** [comment]
I've tried emmet-core>=0.72.18 with monty==2023.11.3. Still getting the python traceback. The first structure optimization folder will run, but the other folders are empty. Which versions are you using?

**Comment by gpetretto** [comment]
Following the discussion in the other issue I checked and this is not related to the change I made in monty. It is due to a change in pydantic 2.5. I have found the source of the issue. I will open a PR on monty to address that.

**Comment by utf** [comment]
Thanks very much for checking @gpetretto

**Comment by nhew1994** [comment]
Thanks @gpetretto and @utf.

**Comment by lihaojie87** [comment]
I have the same problem, is there any solution?

**Comment by gpetretto** [comment]
The solution at the moment should be to install pydantic 2.4.2.
As far as I could test this https://github.com/materialsvirtuallab/monty/pull/597 should fix the problem, but I am afraid that, until that PR is merged, downgrading pydantic is the only option.

**Comment by utf** [comment]
This is now fixed in version 0.1.14
