### ISSUE TITLE
BUG: Pytest on Python 3.8, Windows

### ISSUE THREAD

**Issue by arosen93** [materialsproject/atomate2#63]
I am unsuccessful in running the test suite on Windows, Python 3.8. 

In a fresh Python 3.8 environment, I've done:
```
pip install -r requirements.txt
pip install .[tests]
pytest
```
but all the jobs/flows fail due to 
```python
Traceback (most recent call last):
  File "C:\Users\asros\miniconda3\envs\atomate2\lib\site-packages\jobflow\managers\local.py", line 98, in _run_job
    response = job.run(store=store)
  File "C:\Users\asros\miniconda3\envs\atomate2\lib\site-packages\jobflow\core\job.py", line 524, in run
    response = function(*self.function_args, **self.function_kwargs)
  File "C:\Users\asros\miniconda3\envs\atomate2\lib\site-packages\atomate2\vasp\jobs\base.py", line 147, in make
    run_vasp(**self.run_vasp_kwargs)
  File "C:\Users\asros\miniconda3\envs\atomate2\lib\site-packages\atomate2\vasp\run.py", line 167, in run_vasp
    c.run()
  File "C:\Users\asros\miniconda3\envs\atomate2\lib\site-packages\custodian\custodian.py", line 367, in run
    self._run_job(job_n, job)
  File "C:\Users\asros\miniconda3\envs\atomate2\lib\site-packages\custodian\custodian.py", line 440, in _run_job
    p = job.run()
  File "C:\Users\asros\miniconda3\envs\atomate2\lib\site-packages\custodian\vasp\jobs.py", line 255, in run
    return subprocess.Popen(cmd, stdout=f_std, stderr=f_err)  # pylint: disable=R1732
  File "C:\Users\asros\miniconda3\envs\atomate2\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\asros\miniconda3\envs\atomate2\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by utf** [comment]
That's really odd. It seems like `run_vasp` isn't get mocked successfully...

In particular, this line means that `run_vasp` should never be called an instead `mock_run_vasp` will be called: https://github.com/materialsproject/atomate2/blob/fe5d8a6786f779f13bb3b9ef742a2e5d40c9b5b0/tests/vasp/conftest.py#L81

It's not clear why this works on linux and Mac but not Windows.

I guess we should also add windows to the CI environment.

**Comment by arosen93** [comment]
I don't think there's anything more insightful in here, but I've attached the full `pytest` log here in case it helps:
[test.txt](https://github.com/materialsproject/atomate2/files/7944684/test.txt)

It does seem like it's trying to do `run_vasp`.

**Comment by arosen93** [comment]
This was also a really dumb mistake on my part with what I had pulled. I apologize...

**Comment by utf** [comment]
No worries! Glad it wasn't a bug fix.
