### ISSUE TITLE
BUG:Error in storing/processing lobster output

### ISSUE THREAD

**Issue by edansi** [materialsproject/atomate2#681]
**Describe the bug**
When running the lobster workflow on BaTiO3, all calculations including lobster work well and i get the output files including e.g. automatic_cohp plots. However, there seems to be an error somewhere in the post processing or storing the output in the database. I always get the following error output: 

```
Traceback (most recent call last):
  File "/cluster/home/esimmen/.conda/envs/atomate2/lib/python3.9/site-packages/fireworks/core/rocket.py", line 261, in run
    m_action = t.run_task(my_spec)
  File "/cluster/home/esimmen/.conda/envs/atomate2/lib/python3.9/site-packages/jobflow/managers/fireworks.py", line 175, in run_task
    response = job.run(store=store)
  File "/cluster/home/esimmen/.conda/envs/atomate2/lib/python3.9/site-packages/jobflow/core/job.py", line 583, in run
    response = function(*self.function_args, **self.function_kwargs)
  File "/cluster/home/esimmen/.conda/envs/atomate2/lib/python3.9/site-packages/atomate2/lobster/jobs.py", line 103, in make
    return LobsterTaskDocument.from_directory(
  File "/cluster/home/esimmen/.conda/envs/atomate2/lib/python3.9/site-packages/monty/dev.py", line 100, in decorated
    return _callable(*args, **kwargs)
  File "/cluster/home/esimmen/.conda/envs/atomate2/lib/python3.9/site-packages/atomate2/lobster/schemas.py", line 795, in from_directory
    ) = CondensedBondingAnalysis.from_directory(
  File "/cluster/home/esimmen/.conda/envs/atomate2/lib/python3.9/site-packages/atomate2/lobster/schemas.py", line 357, in from_directory
    describe = Description(analysis_object=analyse)
  File "/cluster/home/esimmen/.conda/envs/atomate2/lib/python3.9/site-packages/lobsterpy/cohp/describe.py", line 27, in __init__
    self.set_description()
  File "/cluster/home/esimmen/.conda/envs/atomate2/lib/python3.9/site-packages/lobsterpy/cohp/describe.py", line 120, in set_description
    else bond_info[0]
IndexError: list index out of range                               
``` 
I'm not quite sure why this happens but I think it's a bug because everything works fine with the MgO example and my colleague was able to reproduce the error.

**To Reproduce**
I used the following code for creating the workflow with the attached CONTCAR file: 
```python
# WORKFLOW
from fireworks import LaunchPad
from atomate2.vasp.flows.lobster import VaspLobsterMaker
from atomate2.vasp.powerups import update_user_incar_settings, update_user_potcar_settings, update_user_kpoints_settings
from jobflow.managers.fireworks import flow_to_workflow

# PYMATGEN
from pymatgen.io.vasp.inputs import Poscar, Kpoints, Incar
from pymatgen.core import Structure

import numpy as np

def lobster_workflow(structure, name, kpts=[8,8,1], NCORE=8, KPAR=4, dry_run=False,ISIF=3, ENCUT=650, GGA='PS', SIGMA = 0.05, ISMEAR = 0, 
                EDIFF=1e-5, ISYM=2, EDIFFG=-1e-2, potcar_dict={"Ba": "Ba_sv", "Ni": "Ni_pv", "O": "O", "Sm": "Sm_3", "Ti": "Ti_sv"}, non_spin_pol = True, no_U = True):
        # Maker
        r_maker = VaspLobsterMaker()
        
        # INCAR
        incar_settings = {"ALGO":"Normal", "GGA":GGA,'EDIFF':EDIFF,'ISMEAR':ISMEAR, "SIGMA":SIGMA, 'ISIF':ISIF,"EDIFFG": EDIFFG, 'ENCUT':ENCUT, "ENAUG": None, "NELM":100, "PREC": None, "LREAL": "Auto", "LMIXTAU": None, "LASPH": None}
        if non_spin_pol:
            incar_settings_2 = {"ISPIN":None, "MAGMOM":None}
            incar_settings.update(incar_settings_2)
        if no_U:
            incar_settings_3 = {"LDAU": False, "LDAUJ": None, "LDAUL": None, "LDAUPRINT": None, "LDAUTYPE": None, "LDAUU": None, "LMAXMIX": None}
            incar_settings.update(incar_settings_3)
        r_maker_2 = update_user_incar_settings(r_maker, incar_settings)
        
        # Parallelization
        r_maker_3 = update_user_incar_settings(r_maker_2, {"NCORE":NCORE, "KPAR":KPAR})
        
        # Potcar
        r_maker_4 = update_user_potcar_settings(r_maker_3, potcar_dict)
        
        # Kpoints
        r_maker_5 = update_user_kpoints_settings(r_maker_4, Kpoints(kpts = [kpts]))
        static_flow = r_maker_5.make(structure)
        
        # update the fireworker of the Lobster jobs
        for job, _ in static_flow.iterflow():
            config = {"manager_config": {"_fworker": "vasp_c"}}
            if "get_lobster" in job.name:
                config["response_manager_config"] = {"_fworker": "lobster"}
            job.update_config(config)
        
        # metadata
        static_flow.update_metadata({"calc_name": name})
        
        # workflow
        wf = flow_to_workflow(static_flow)
        lpad = LaunchPad.auto_load()
        if not dry_run:
            lpad.add_wf(wf)
        else:
            print('Dry run, not submitting workflow')
``` 
and
```python
structure = Structure.from_file('/home/esimmen/PhD/heterostructs/BTO_SNO/metallic/no_tilts/bto_bulk/polar/2_el_relax/CONTCAR')
jobname = "cohp, bto_bulk, str=sto"
lobster_workflow(structure, jobname, ISMEAR = -5, SIGMA = None)
```

**Comment by JaGeo** [comment]
Thanks for reporting. We are working on the LOBSTER workflows anyway at the moment. We will check. (cc: @naik-aakash )

**Comment by JaGeo** [comment]
@edansi Could you maybe also provide a structure? If not publically, you can send it via mail to us janine.george at bam.de .

**Comment by naik-aakash** [comment]
Thanks @edansi for reporting the issue. Will look into this issue

**Comment by edansi** [comment]
@JaGeo I forgot to attach it before. Here it is: 
[CONTCAR.zip](https://github.com/materialsproject/atomate2/files/13960307/CONTCAR.zip)

**Comment by JaGeo** [comment]
@edansi Thanks! To me, it looks more like a LobsterPy issue at the moment but we will check. Thanks!

**Comment by edansi** [comment]
I forgot to mention this in the post above but I used a Vasp version that only relaxes along the c-axis. But I don't think this would change the error I get.

**Comment by naik-aakash** [comment]
Thanks @edansi for reporting the issue, this problem should be fixed now and with next release of LobsterPy, this error you should not encounter in future.

We will also update the LobsterTask doc schema to have possibility to tweak the LobsterPy args as well , so you will have more flexibility with automatic bonding analysis outputs too

**Comment by JaGeo** [comment]
This release of LobsterPy should fix the issue: https://github.com/JaGeo/LobsterPy/releases/tag/v0.3.5

Let us know if not. We will also update the atomate2 requirements in an additional pull request. Please feel free to update LobsterPy before and test again.

**Comment by edansi** [comment]
Thank you! I just tested it and it now for me!
