### ISSUE TITLE
BUG: Vasprun cannot find potcar 

### ISSUE THREAD

**Issue by mjwen** [materialsproject/atomate2#705]
**Describe the bug**

Example workflow in the doc cannot finish due to Vasprun validation. Here is the stacktrace: 
```
  9 2024-02-06 23:18:26,078 INFO Started executing jobs locally
 10 2024-02-06 23:18:26,083 INFO Starting job - static (b59b4d9f-ad0f-4518-b58d-a32111ecde96)
 11 /home/mjwen/Packages/atomate2/src/atomate2/vasp/sets/base.py:619: BadInputSetWarning: POTCAR data with symbol Si is not known by pymatgen     to correspond with the selected potcar_functional PBE_54. This POTCAR is known to correspond with functionals ['PBE_64', 'PBE_54_W_HASH'    , 'PBE_52_W_HASH']. Please verify that you are using the right POTCARs!
 12   warnings.warn(
 13 Failed to load vasprun.xml
 14 Traceback (most recent call last):
 15   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/site-packages/custodian/vasp/validators.py", line 30, in check
 16     Vasprun("vasprun.xml")
 17   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/site-packages/pymatgen/io/vasp/outputs.py", line 296, in __init__
 18     self.update_potcar_spec(parse_potcar_file)
 19   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/site-packages/pymatgen/io/vasp/outputs.py", line 1054, in update_potcar_spe    c
 20     if potcar := self.get_potcars(path):
 21                  ^^^^^^^^^^^^^^^^^^^^^^
 22   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/site-packages/pymatgen/io/vasp/outputs.py", line 1010, in get_potcars
 23     f"{search_path}/{fn}" for fn in os.listdir(search_path) if fn.startswith("POTCAR") and ".spec" not in fn
 24                                     ^^^^^^^^^^^^^^^^^^^^^^^
 25 FileNotFoundError: [Errno 2] No such file or directory: ''
 26 Validation failed: VasprunXMLValidator
 27 2024-02-06 23:18:36,422 INFO static failed with exception:
 28 Traceback (most recent call last):
 29   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/site-packages/jobflow/managers/local.py", line 114, in _run_job
 30     response = job.run(store=store)
 31                ^^^^^^^^^^^^^^^^^^^^
 32   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/site-packages/jobflow/core/job.py", line 583, in run
 33     response = function(*self.function_args, **self.function_kwargs)
 34                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 35   File "/home/mjwen/Packages/atomate2/src/atomate2/vasp/jobs/base.py", line 227, in make
 36     run_vasp(**self.run_vasp_kwargs)
 37   File "/home/mjwen/Packages/atomate2/src/atomate2/vasp/run.py", line 165, in run_vasp
 38     custodian_manager.run()
 39   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/site-packages/custodian/custodian.py", line 383, in run
 40     self._run_job(job_n, job)
 41   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/site-packages/custodian/custodian.py", line 511, in _run_job
 42     raise ValidationError(s, True, v)
 43 custodian.custodian.ValidationError: Validation failed: VasprunXMLValidator
 44
 45 2024-02-06 23:18:36,422 INFO Finished executing jobs locally
```

I did a quick debug, and here is what I found: 
- in line 23, `search_path` is an empty string
- it is empty because `path=True` and `self.filename=vasprun.xml` in the below snippet (line 22 above, i.e. /pymatgen/io/vasp/outputs.py)
```
1008             search_path = os.path.split(self.filename)[0] if path is True else str(path)
1009             potcar_paths = [
1010                 f"{search_path}/{fn}" for fn in os.listdir(search_path) if fn.startswith("POTCAR") and ".spec" not in fn
1011             ] 
```

I have no idea why this happens - not sure it is because of pymatgen, custodian, or atomate2. Anyone has ideas/suggestions before I spend more time diving into it? 

It seems like a pymatgen error: I would hope `search_path` be `.` if `self.filename` is a string but not a Path. 

 
**To Reproduce**
1. I used the latest atomate2, commit [8b1ee04](https://github.com/materialsproject/atomate2/commit/8b1ee044674bb75ee9cd025d9ffc6d883f772fa5)
3. I installed using `pip install -e .`
4. I ran the example job in the doc (note, RelaxMaker is replaced by StaticMaker to speed it up) https://materialsproject.github.io/atomate2/user/install.html 
5. pymatgen - v2024.1.27

**Comment by mjwen** [comment]
@janosh Seems like a pymatgen bug. Any idea?

**Comment by mjwen** [comment]
Never mind: I confirm this is a pymatgen bug, and it got fixed here https://github.com/materialsproject/pymatgen/commit/d677a0a6c041450eb06b3ab71bafa175c41e4e4d
