### ISSUE TITLE
BUG: ElasticMaker deepcopy error

### ISSUE THREAD

**Issue by mjwen** [materialsproject/atomate2#707]
**Describe the bug**

VASP ElasticMaker `run_elastic_deformations` cannot finish because of deepcopy error. Seems it is related to deepcopy `TransformedStructure`,but it is not obvious to me why this happens. 

```
  1 2024-02-07 22:52:52,184 INFO Started executing jobs locally
  2 2024-02-07 22:52:52,192 INFO Starting job - tight relax 1 (c00cd942-aac0-45cd-b07c-9fa0e9e12007)
  3 2024-02-07 22:53:24,604 INFO Finished job - tight relax 1 (c00cd942-aac0-45cd-b07c-9fa0e9e12007)
  4 2024-02-07 22:53:24,605 WARNING Response.stored_data is not supported with local manager.
  5 2024-02-07 22:53:24,606 INFO Starting job - tight relax 2 (c9624e3d-87aa-4f1e-9cf6-44c1ef57dcf6)
  6 2024-02-07 22:53:47,392 INFO Finished job - tight relax 2 (c9624e3d-87aa-4f1e-9cf6-44c1ef57dcf6)
  7 2024-02-07 22:53:47,392 WARNING Response.stored_data is not supported with local manager.
  8 2024-02-07 22:53:47,393 INFO Starting job - generate_elastic_deformations (dff67507-80af-42e5-bb94-ff54adef9500)
  9 2024-02-07 22:53:48,712 INFO Finished job - generate_elastic_deformations (dff67507-80af-42e5-bb94-ff54adef9500)
 10 2024-02-07 22:53:48,713 INFO Starting job - run_elastic_deformations (da08e73b-9c6f-48fd-a860-a2eae9f55a9b)
 11 2024-02-07 22:53:49,234 INFO run_elastic_deformations failed with exception:
 12 Traceback (most recent call last):
 13   File "/home/mjwen/Packages/jobflow/src/jobflow/managers/local.py", line 114, in _run_job
 14     response = job.run(store=store)
 15                ^^^^^^^^^^^^^^^^^^^^
 16   File "/home/mjwen/Packages/jobflow/src/jobflow/core/job.py", line 583, in run
 17     response = function(*self.function_args, **self.function_kwargs)
 18                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 19   File "/home/mjwen/Packages/atomate2/src/atomate2/common/jobs/elastic.py", line 150, in run_elastic_deformations
 20     relax_job = elastic_relax_maker.make(deformed_structure, **elastic_job_kwargs)
 21                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 22   File "/home/mjwen/Packages/jobflow/src/jobflow/core/job.py", line 195, in get_job
 23     return Job(
 24            ^^^^
 25   File "/home/mjwen/Packages/jobflow/src/jobflow/core/job.py", line 329, in __init__
 26     self.function = deepcopy(function)
 27                     ^^^^^^^^^^^^^^^^^^
 28   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/copy.py", line 146, in deepcopy
 29     y = copier(x, memo)
 30         ^^^^^^^^^^^^^^^
 31   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/copy.py", line 238, in _deepcopy_method
 32     return type(x)(x.__func__, deepcopy(x.__self__, memo))
 33                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
 34   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/copy.py", line 172, in deepcopy
 35     y = _reconstruct(x, memo, *rv)
 36         ^^^^^^^^^^^^^^^^^^^^^^^^^^
 37   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/copy.py", line 271, in _reconstruct
 38     state = deepcopy(state, memo)
 39             ^^^^^^^^^^^^^^^^^^^^^
 40   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
 42         ^^^^^^^^^^^^^^^
 43   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/copy.py", line 231, in _deepcopy_dict
 44     y[deepcopy(key, memo)] = deepcopy(value, memo)
 45                              ^^^^^^^^^^^^^^^^^^^^^
 46   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/copy.py", line 146, in deepcopy
 47     y = copier(x, memo)
 48         ^^^^^^^^^^^^^^^
 49   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/copy.py", line 231, in _deepcopy_dict
 50     y[deepcopy(key, memo)] = deepcopy(value, memo)
 51                              ^^^^^^^^^^^^^^^^^^^^^
 52   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/copy.py", line 172, in deepcopy
 53     y = _reconstruct(x, memo, *rv)
 54         ^^^^^^^^^^^^^^^^^^^^^^^^^^
 55   File "/project/wen/mjwen/conda/envs/atomate2/lib/python3.11/copy.py", line 272, in _reconstruct
 56     if hasattr(y, '__setstate__'):
 57        ^^^^^^^^^^^^^^^^^^^^^^^^^^
 58   File "/home/mjwen/Packages/pymatgen/pymatgen/alchemy/materials.py", line 90, in __getattr__
 59     return getattr(self.final_structure, name)
 60                    ^^^^^^^^^^^^^^^^^^^^
 61   File "/home/mjwen/Packages/pymatgen/pymatgen/alchemy/materials.py", line 90, in __getattr__
 62     return getattr(self.final_structure, name)
 63                    ^^^^^^^^^^^^^^^^^^^^
 64   File "/home/mjwen/Packages/pymatgen/pymatgen/alchemy/materials.py", line 90, in __getattr__
 65     return getattr(self.final_structure, name)
 66                    ^^^^^^^^^^^^^^^^^^^^
   [Previous line repeated 978 more times]
 68 RecursionError: maximum recursion depth exceeded
 69
 70 2024-02-07 22:53:49,235 INFO Starting job - fit_elastic_tensor (1befab8c-82b3-4e1e-9f14-79465123a3d9)
 71 2024-02-07 22:53:49,590 INFO fit_elastic_tensor failed with exception:
 72 Traceback (most recent call last):
 73   File "/home/mjwen/Packages/jobflow/src/jobflow/managers/local.py", line 114, in _run_job
 74     response = job.run(store=store)
 75                ^^^^^^^^^^^^^^^^^^^^
 76   File "/home/mjwen/Packages/jobflow/src/jobflow/core/job.py", line 583, in run
 77     response = function(*self.function_args, **self.function_kwargs)
 78                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 79   File "/home/mjwen/Packages/atomate2/src/atomate2/common/jobs/elastic.py", line 210, in fit_elastic_tensor
 80     for data in deformation_data:
 81 TypeError: 'NoneType' object is not iterable
 82
 83 2024-02-07 22:53:49,590 INFO Finished executing jobs locally
```

**To Reproduce**

1. This is the file generated the above stack trace:
```python
from jobflow import run_locally
from pymatgen.core import Structure
from atomate2.vasp.flows.elastic import ElasticMaker

structure = Structure(
     lattice=[[0, 2.13, 2.13], [2.13, 0, 2.13], [2.13, 2.13, 0]],
     species=["Mg", "O"],
     coords=[[0, 0, 0], [0.5, 0.5, 0.5]],
)
flow = ElasticMaker().make(structure)
run_locally(flow, create_folders=True)
```

2. Latest pymatgen (commit fe4c7c8b7921f6), jobflow (commit 5627622e943), and atomate2(commit 8b1ee044674). All are Feb 5 commits. 

Tagging @JaGeo. Seems you have recently refactored the elastic workflow. Any idea?

**Comment by JaGeo** [comment]
It reads like there is a recursion but I don't think this has anything todo with the changes made to enable the forcefields in the elastic maker. Sorry.

**Comment by mjwen** [comment]
@JaGeo Thanks and no worries! I feel it is a bug coming from pymatgen - will need to dig deeper.

**Comment by mjwen** [comment]
Confirmed that this is due to a bug in pymatgen recently introduced. Fix in https://github.com/materialsproject/pymatgen/pull/3617. 

Will close this once that is merged.

**Comment by utf** [comment]
Thanks again for fixing @mjwen
